Exit enter_juneberry_container if setup_workspace returns non-zero (#60)
* Exit enter_juneberry_container if setup_workspace returns non-zero

* added additional logging, reordered some functions

* change workspace key to workspace_root

diff --git a/docker/enter_juneberry_container b/docker/enter_juneberry_container
--- a/docker/enter_juneberry_container
+++ b/docker/enter_juneberry_container
@@ -130,6 +130,9 @@ else
   ${PROJ}/juneberry/scripts/setup_workspace.py -p ${PROJ} -w ${WS}
   if [ $? -eq 0 ]; then
     WS="-v ${WS}:/workspace -w //workspace"
+  else
+    echo "Unable to setup workspace in ${WS}. Exiting."
+    exit 1
   fi
 fi
 
